source ${genode_dir}/repos/gart/run/test/libnativebridge/variables.inc

append build_components {
	test/libnativebridge/ReSetupNativeBridge
}

append config {
	<start name="test_ReSetupNativeBridge">
		<resource name="RAM" quantum="4M"/>
		<config>
			<vfs>
				<dir name="tmp"> <ram/> </dir>
				<dir name="dev">
               <log/>
               <inline name="rtc">2018-01-01 00:01</inline>
            </dir>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" />
		</config>
	</start>
}

append boot_modules {
	test_ReSetupNativeBridge
}

source ${genode_dir}/repos/gart/run/test/libnativebridge/build.inc

run_genode_until {.*child "test_ReSetupNativeBridge" exited with exit value 0} $timeout
