#
# Build
#

set build_components {
	core init timer
	lib/vfs/jitterentropy
	lib/vfs/pipe
	lib/gart_libart-simulator
	lib/gart_libcore
	lib/gart_libopenjdk
	test/dummy_java_libs
	test/libart-compiler
	test/gart_gtest/AbstractMethod
	test/gart_gtest/DexToDexDecompiler
	test/gart_gtest/ExceptionHandle
	test/gart_gtest/Interfaces
	test/gart_gtest/MultiDex
	test/gart_gtest/MyClassNatives
	test/gart_gtest/ProfileTestMultiDex
	test/gart_gtest/StaticLeafMethods
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

proc test_args {} { return "$::env(TEST_ARGS)" }
proc timeout {} { return "$::env(TIMEOUT)" }

set config ""
append config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="CAP"/>
		<service name="RM"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="1000"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="libart-compiler_test">
		<resource name="RAM" quantum="450M"/>
		<config ld_verbose="no">
			<vfs>
				<dir name="tmp"> <ram/> </dir>
				<dir name="data">
					<dir name="dalvik-cache">
						<ram/>
					</dir>
				</dir>
				<dir name="dev">
					<dir name="pipe"><pipe/></dir>
					<log/>
					<inline name="rtc">2018-01-01 00:01</inline>
					<jitterentropy name="random"/>
				</dir>
				<dir name="system">
					<dir name="framework">
						<tar name="framework.tar"/>
					</dir>
					<dir name="etc">
						<inline name="public.libraries.txt"></inline>
						<inline name="llndk.libraries.txt"></inline>
						<inline name="vndksp.libraries.txt"></inline>
						<inline name="event-log-tags"># dummy</inline>
					</dir>
					<dir name="usr">
						<dir name="icu">
							<tar name="icu.tar"/>
						</dir>
					</dir>
				</dir>
				<dir name="test">
					<tar name="testdata.tar"/>
				</dir>
			</vfs>
			<libc stdin="/dev/log" stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" pipe="/dev/pipe" rng="/dev/random" />
			<start name="/bin/libart-compiler_test">
				<arg value="} [test_args] {"/>
				<env name="ANDROID_DATA" value="/data"/>
				<env name="ANDROID_ROOT" value="/system"/>
			</start>
		</config>
	</start>
</config>}

install_config $config

#
# Boot image
#

exec tar --transform s/.jar/-testdex.jar/ -cf bin/framework.tar -C bin core-libart.jar core-oj.jar

exec cp [genode_dir]/repos/gart/test/data/art-gtest-VerifierDeps.jar \
	[genode_dir]/repos/gart/test/data/art-gtest-VerifierDepsMulti.jar \
	bin/

exec tar -cf bin/testdata.tar -C bin \
	art-gtest-AbstractMethod.jar \
	art-gtest-DexToDexDecompiler.jar \
	art-gtest-ExceptionHandle.jar \
	art-gtest-Interfaces.jar \
	art-gtest-MultiDex.jar \
	art-gtest-MyClassNatives.jar \
	art-gtest-ProfileTestMultiDex.jar \
	art-gtest-StaticLeafMethods.jar \
	art-gtest-VerifierDeps.jar \
	art-gtest-VerifierDepsMulti.jar

# generic modules
set boot_modules {
	core init timer ld.lib.so
	vfs.lib.so libc.lib.so libm.lib.so stdcxx.lib.so
	vfs_jitterentropy.lib.so
	vfs_pipe.lib.so
	gtest.lib.so gart_liblog.lib.so
	gart_libart.lib.so
	gart_libbacktrace.lib.so
	gart_libbase.lib.so
	gart_libcutils.lib.so
	gart_libdexfile.lib.so
	gart_libnativehelper.lib.so
	gart_libutils.lib.so
	gart_libvndksupport.lib.so
	gart_libz.lib.so
	gart_libziparchive.lib.so
	gart_libicuuc.lib.so
	gart_liblz4.lib.so
	gart_libmetricslogger.lib.so
	gart_libnativebridge.lib.so
	gart_libnativeloader.lib.so
	gart_libsigchain.lib.so
	gart_liblzma.lib.so
	gart_libvixl-arm.lib.so
	gart_libvixl-arm64.lib.so
	gart_libart-disassembler.lib.so
	gart_libart-compiler.lib.so
	gart_libicui18n.lib.so
	gart_libcore.lib.so
	gart_libcrypto.lib.so
	gart_libexpat.lib.so
	gart_libcore.lib.so
	gart_libopenjdk.lib.so
	gart_libopenjdkjvm.lib.so
	gart_libart-simulator.lib.so
	libart-compiler_test
	framework.tar
	testdata.tar
	icu.tar
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

append qemu_args " -m 1024 -nographic "
run_genode_until {.*Global test environment tear-down} [timeout]
