#
# Build
#

set build_components {
	core init timer
	test/libutils
   test/libutils_test_libs
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

install_config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="CAP"/>
		<service name="RM"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="1000"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="libutils_test">
		<resource name="RAM" quantum="32M"/>
		<config ld_verbose="yes" ld_bind_now="no">
			<vfs>
			    <dir name="tmp"> <ram/> </dir>
				<dir name="data"> <dir name="local"> <dir name="tmp"> <ram/> </dir> </dir> </dir>
				<dir name="dev">
               <log/>
               <inline name="rtc">2018-01-01 00:01</inline>
               <inline name="random">3d32200c56d42fac0ed8dada9d9b33e7</inline>
            </dir>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc"/>
         <start name="/bin/libutils_test">
            <!--
                  Death test unsupported:
                     VectorTest.SetCapacity_Overflow
                     VectorTest._grow_OverflowSize
                     VectorTest._grow_OverflowCapacityDoubling
                     VectorTest._grow_OverflowBufferAlloc
                     UnicodeTest.InvalidUtf8OverreadDetected
                  mprotect() is unsupported:
                     UnicodeTest.strstr16EmptyTarget_bug
                  No RTC in CI:
                     SystemClock.SystemClock
            -->
            <arg value="--gtest_filter=-VectorTest.SetCapacity_Overflow:VectorTest._grow_OverflowSize:VectorTest._grow_OverflowCapacityDoubling:VectorTest._grow_OverflowBufferAlloc:UnicodeTest.InvalidUtf8OverreadDetected:UnicodeTest.strstr16EmptyTarget_bug:SystemClock.SystemClock"/>
         </start>
		</config>
      <route>
         <service name="Nic"> <child name="nic_router"/> </service>
         <any-service> <parent/> <any-child/> </any-service>
      </route>
	</start>
</config>}

#
# Boot image
#

# generic modules
set boot_modules {
	core init timer ld.lib.so
	vfs.lib.so libc.lib.so libm.lib.so stdcxx.lib.so gtest.lib.so
   gart_libvndksupport.lib.so gart_liblog.lib.so gart_libbase.lib.so
   gart_libz.lib.so gart_libcutils.lib.so gart_libutils.lib.so
   gart_libutils_tests_singleton1.lib.so gart_libutils_tests_singleton2.lib.so
	libutils_test
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

append qemu_args " -m 512 -nographic "
run_genode_until {.*child "libutils_test" exited with exit value 0} 120
