#
# Build
#

set build_components {
	core init timer
	test/libziparchive
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

install_config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="CAP"/>
		<service name="RM"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="1000"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="libziparchive_test">
		<resource name="RAM" quantum="128M"/>
		<config>
			<vfs>
			    <dir name="tmp"> <ram/> </dir>
            <dir name="data">
               <dir name="local">
				      <dir name="tmp">
                     <ram/>
                  </dir>
               </dir>
            </dir>
            <dir name="testdata">
				   <tar name="testdata.tar"/>
            </dir>
				<dir name="dev">
					<log/>
               <inline name="rtc">2018-01-01 00:01</inline>
               <inline name="random">3d32200c56d42fac0ed8dada9d9b33e7</inline>
				</dir>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" />
         <start name="/bin/libziparchive_test">
            <arg value="--test_data_dir=/testdata"/>
         </start>
		</config>
	</start>
</config>}

#
# Boot image
#

# generic modules
set boot_modules {
	core init ld.lib.so timer
	libc.lib.so libm.lib.so vfs.lib.so
	stdcxx.lib.so gtest.lib.so
	gart_liblog.lib.so gart_libbase.lib.so gart_libziparchive.lib.so
   gart_libvndksupport.lib.so gart_libcutils.lib.so gart_libutils.lib.so gart_libz.lib.so
	libziparchive_test
	testdata.tar
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

append qemu_args " -m 512 -nographic "
run_genode_until {.*child "libziparchive_test" exited with exit value 0} 100
